
CREATE TABLE IF NOT EXISTS "PerfomanceCounterValues" (
	"AppId" SMALLINT NOT NULL DEFAULT E'0',
	"CounterId" SMALLINT NOT NULL,
	"Timestamp" TIMESTAMP NOT NULL,
	"Value" REAL NULL DEFAULT NULL,
	PRIMARY KEY ("AppId", "CounterId", "Timestamp")
);

CREATE TABLE IF NOT EXISTS "Applications" (
	"AppId" SMALLINT NULL DEFAULT NULL,
	"AppName" VARCHAR NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "CounterNames" (
	"Id" SMALLINT NOT NULL,
	"Name" VARCHAR NULL DEFAULT NULL,
	PRIMARY KEY ("Id")
);